clone:
  git:
    image: plugins/git:next

workspace:
  base: /test
  path: qa-automation

matrix:
  COMPOSER_VERSION:
    - 1
    - 2
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.4
    - 8.0
    - 8.1

pipeline:
  composer-install:
    group: init
    image: fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - composer self-update --${COMPOSER_VERSION=1}
      - composer install --ansi --no-suggest --no-progress
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      matrix:
        COMPOSER_BOUNDARY: highest

  composer-install-lowest:
    group: init
    image: fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - composer self-update --${COMPOSER_VERSION=1}
      - composer update --prefer-${COMPOSER_BOUNDARY=lowest} --prefer-stable --ansi --no-suggest --no-progress
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  phpcs:
    image: fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - ./vendor/bin/phpcs -p
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  phpunit:
    image: fpfis/httpd-php:${PHP_VERSION=7.3}-ci
    commands:
      - ./vendor/bin/phpunit phpcs/
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
