<?php

/**
 * @file
 * This file contains code to testing purpose only.
 */

/**
 * Implments hook_install()
 */
function Update7000Error_install() {

  FunctionsDeclarationsError_update_7001();
}


/**
 * Implements hook_enable().
 */
function Update7000Error_enable() {
  drupal_set_message(t("The feature jrccties_core has been enabled."), 'status');

}

class GettingJiggyWithIt {

  public function NaNaNaNaNaNa() {
    return 'hook';
  }
}

interface YouTouchMy {

  public function Tralala();
}

function plop($super, $cali, $fragilistic, $expialidocious) {
  if ($super == $cali) {
    return 'Marry';
  }
  if ($fragilistic == $expialidocious) {
    return 'Poppins';
  }
}

function roll() {
  for($i = 0; $i < 100; $i++) {
    echo 'Never gonna give you up, never gonna give you up';
  }
  for($i = 0; $i < 100; $i++) {
    echo 'Never gonna tell a lie and hurt you';
  }
}

function guessWhosBack($c, $o, $r, $e, $t, $e, $a, $m) {
  if ($c == $o) {
    return $c.$o.$r.$e;
  } else {
    return $t.$e.$a.$m;
  }
}