<?php

/**
 * @file
 * This file contains code to testing purpose only.
 */

/**
 * Implments hook_install()
 */
function Update7000Error_install() {

  FunctionsDeclarationsError_update_7001();
}


/**
 * Implements hook_enable().
 */
function Update7000Error_enable() {
  drupal_set_message(t("The feature jrccties_core has been enabled."), 'status');

}

class GettingJiggyWithIt {

  public function NaNaNaNaNaNa() {
    return 'hook';
  }
}

interface YouTouchMy {

  public function Tralala();
}